{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.tentus",
    "module": "commons",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "commons-1.0.7.jar",
          "url": "commons-1.0.7.jar",
          "size": 13138,
          "sha512": "2ab213f73f6eb0843c559f9db7cd584cebf8b13be216236878a4dc43d54f0b9714a169e73c87d200972f1bf5c0f165651aa0c23c856fc0ad5c61f3e60143d78d",
          "sha256": "c09edefdf5fe372bc32f74b6dd1f72614807b44e5af196a1ded73940e3befcec",
          "sha1": "f8427da9e2516854d2dbb843ff898a83b0e90a4e",
          "md5": "e264d449fe0d89c040975ee023e8c411"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "commons-1.0.7.jar",
          "url": "commons-1.0.7.jar",
          "size": 13138,
          "sha512": "2ab213f73f6eb0843c559f9db7cd584cebf8b13be216236878a4dc43d54f0b9714a169e73c87d200972f1bf5c0f165651aa0c23c856fc0ad5c61f3e60143d78d",
          "sha256": "c09edefdf5fe372bc32f74b6dd1f72614807b44e5af196a1ded73940e3befcec",
          "sha1": "f8427da9e2516854d2dbb843ff898a83b0e90a4e",
          "md5": "e264d449fe0d89c040975ee023e8c411"
        }
      ]
    }
  ]
}
